name: CastleSiege
main: me.huntifi.castlesiege.Main
version: 1.1.1
api-version: 1.13
authors: [Huntifi, Greenfoot5]
depends: [Votifier, WorldGuard, NametagEdit, WorldGuard]
softdepend: [LibsDisguises, WorldEdit]
load: STARTUP

permissions:
  # Staff
  castlesiege.admin:
    description: Gives access to all CastleSiege Admin commands
    children:
      castlesiege.developer: true
  castlesiege.developer:
    description: Gives access to all CastleSiege Developer commands
    children:
      castlesiege.moderator: true
  castlesiege.moderator:
    description: Gives access to all CastleSiege Moderator commands
    children:
      castlesiege.chatmod+: true
  castlesiege.chatmod+:
    description: Gives access to all CastleSiege Chatmod+ commands
    children:
      castlesiege.chatmod: true
  castlesiege.chatmod:
    description: Gives access to all CastleSiege Chatmod commands

  # Donator
  castlesiege.high king:
    description: Gives access to all CastleSiege High King commands
    children:
      castlesiege.king: true
  castlesiege.king:
    description: Gives access to all CastleSiege King commands
    children:
      castlesiege.duke: true
  castlesiege.duke:
    description: Gives access to all CastleSiege Count commands
    children:
      castlesiege.baron: true
  castlesiege.baron:
    description: Gives access to all CastleSiege Baron commands
    children:
      castlesiege.noble: true
  castlesiege.noble:
    description: Gives access to all CastleSiege Noble commands
    children:
      castlesiege.esquire: true
  castlesiege.esquire:
    description: Gives access to all CastleSiege Esquire commands

commands:
  Gmc:
    description: Change your game mode to creative.
    usage: /Gmc
  Gmsp:
    description: Change your game mode to spectator.
    usage: /Gmsp
  Gms:
    description: Change your game mode to survival.
    usage: /Gms
  Gma:
    description: Change your game mode to adventure.
    usage: /Gma
  Giverank:
    description: Gives a rank to the targetted player.
    usage: /Giverank
  Givestaffrank:
    description: Gives a staff rank to the targetted player.
    usage: /Givestaffrank
  Checkrank:
    description: This is a controle check message to see if the database - ranks work.
    usage: /Checkrank
  Togglerank:
    description: Toggle your rank on and off.
    usage: /Togglerank
  Ban:
    description: Ban a player!
    usage: /Ban
  Unban:
    description: Unban a banned player!
    usage: /Unban
  Mute:
    description: Mute a player!
    usage: /Mute
  Unmute:
    description: Unmute a muted player!
    usage: /Unmute
  Kick:
    description: Kick a player from the server!
    usage: /Kick
  Vanish:
    description: Vanish into the void!
    usage: /Vanish
  Playerid:
    description: Returns the target player's UUID.
    usage: /Playerid
  Mystats:
    description: Opens a book that shows you your stats.
    usage: /Mystats
  s:
    description: Talk in staff chat.
    usage: /s
  togglerank:
    description: Toggles the rank
    usage: /togglerank
  CheckFlagList:
    description: check helmsdeep arraylists
    usage: /CheckFlagList
  Kickall:
    description: Kick all players from the server
    usage: /Kickall
  Unsessionmute:
    description: Un-sessionmutes the player.
    usage: /Unsessionmute
  sessionmute:
    description: Session mute the player.
    usage: /sessionmute
  Givevoter:
    description: Not for players, this is a console command.
    usage: /Givevoter
  Givevote:
    description: Moderator command to give players their votes.
    usage: /Givevote

  CSReload:
    description: Reloads the Castle Siege Plugin
    usage: /csreload
  NextMap:
    description: Skips the current map and goes directly to the next one.
    usage: /nextmap
  Switch:
    description: Switches teams.
    usage: /switch
    aliases: sw
  SaveMap:
    description: Saves any changes made to the current map
    usage: /savemap
  Suicide:
    description: commit die
    usage: /suicide
    aliases: sui

  # Chat
  Message:
    description: Privately message a player
    usage: /msg <player> <message>
    aliases:
      - msg
      - m
      - whisper
      - w
  Reply:
    description: Reply to the last player that sent you a private message
    usage: /r <message>
    aliases: r
  TeamChat:
    description: Talk in team-chat
    usage: /t <message>
    aliases:
      - team
      - t

  # Info
  Discord:
    description: Gives the link to our discord
    usage: /discord
  Maps:
    description: Shows all maps in rotation
    usage: /maps
  MVP:
    description: Shows the current MVP(s)
    usage: /mvp(s)
    aliases: mvps
  Ping:
    description: Shows your current ping
    usage: /ping
  Rules:
    description: Shows the rules
    usage: /rules
  Teams:
    description: Shows the size and name of all teams on the current map
    usage: /teams

  # Staff
  Fly:
    description: Allows staff members to fly
    usage: /fly
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!

  # Kits
  Kit:
    description: Open the GUI for selecting kits
    usage: /kit <category>
  Archer:
    description: Selects the archer kit
    usage: /archer
  Berserker:
    description: Selects the berserker kit
    usage: /berserker
  Cavalry:
    description: Selects the cavalry kit
    usage: /cavalry
  Crossbowman:
    description: Selects the crossbowman kit
    usage: /crossbowman
  Engineer:
    description: Selects the engineer kit
    usage: /engineer
  Executioner:
    description: Selects the executioner kit
    usage: /executioner
  FireArcher:
    description: Selects the firearcher kit
    usage: /firearcher
  Halberdier:
    description: Selects the halberdier kit
    usage: /halberdier
  Ladderman:
    description: Selects the ladderman kit
    usage: /ladderman
  Maceman:
    description: Selects the maceman kit
    usage: /maceman
  Medic:
    description: Selects the medic kit
    usage: /medic
  Ranger:
    description: Selects the ranger kit
    usage: /ranger
  Scout:
    description: Selects the scout kit
    usage: /scout
  Shieldman:
    description: Selects the shieldman kit
    usage: /shieldman
  Skirmisher:
    description: Selects the skirmisher kit
    usage: /skirmisher
  Spearman:
    description: Selects the spearman kit
    usage: /spearman
  Swordsman:
    description: Selects the swordsman kit
    usage: /swordsman
  Viking:
    description: Selects the viking kit
    usage: /viking
  Warhound:
    description: Selects the warhound kit
    usage: /warhound
