# How many maps to play before restarting the server
map_count: 3

delays:
  # Seconds before starting the game (players stay in the lobby of the first map)
  game: 0
  # Seconds to keep players in the lobby before the map starts
  lobby: 0
  # How long in seconds players are allowed to spawn at any location and explore the map
  exploration: 0
# Settings for if the game is a match
match:
  enabled: false
  # If players should remain on the same team
  keep_teams: false
  # Overrides map count
  # List the names of the maps being played and in what order
  maps:
    - "Helm's Deep"
    - "Thunderstone"
    - "Elwynn"