name: CastleSiege
main: me.huntifi.castlesiege.Main
version: 1.2.5
api-version: 1.20
authors: [Huntifi, Greenfoot5, kasteelvuur]
depend:
  - Votifier
  - WorldGuard
  - NametagEdit
  - MythicMobs
softdepend:
  - LibsDisguises
  - WorldEdit
  # Packets Stuff
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot
  # End Packets Stuff
load: STARTUP

permissions:
  # Staff
  castlesiege.owner:
    description: Gives access to all CastleSiege Owner commands
    children:
      castlesiege.admin: true
  castlesiege.admin:
    description: Gives access to all CastleSiege Admin commands
    children:
      castlesiege.communitymanager: true
  castlesiege.communitymanager:
    description: Gives access to all the CastleSiege CommunityManager commands
    children:
      castlesiege.developer: true
  castlesiege.developer:
    description: Gives access to all CastleSiege Developer commands
    children:
      castlesiege.moderator: true
  castlesiege.moderator:
    description: Gives access to all CastleSiege Moderator commands
    children:
      castlesiege.chatmod+: true
      minecraft.command.gamemode: true
  castlesiege.chatmod+:
    description: Gives access to all CastleSiege Chatmod+ commands
    children:
      castlesiege.chatmod: true
  castlesiege.chatmod:
    description: Gives access to all CastleSiege Chatmod commands
    children:
      castlesiege.builder: true
  castlesiege.builder:
    description: Gives access to all CastleSiege builder commands

  # Donator
  castlesiege.high_king:
    description: Gives access to all CastleSiege High King commands
    children:
      castlesiege.king: true
  castlesiege.king:
    description: Gives access to all CastleSiege King commands
    children:
      castlesiege.viceroy: true
  castlesiege.viceroy:
    description: Gives access to all CastleSiege Viceroy commands
    children:
      castlesiege.duke: true
  castlesiege.duke:
    description: Gives access to all CastleSiege Duke commands
    children:
      castlesiege.count: true
  castlesiege.count:
    description: Gives access to all CastleSiege Count commands
    children:
      castlesiege.baron: true
  castlesiege.baron:
    description: Gives access to all CastleSiege Baron commands
    children:
      castlesiege.noble: true
  castlesiege.noble:
    description: Gives access to all CastleSiege Noble commands
    children:
      castlesiege.esquire: true
  castlesiege.esquire:
    description: Gives access to all CastleSiege Esquire commands
  castlesiege.vip:
    description: Gives access to all CastleSiege VIP commands

commands:
  # TODO - These command have yet to be reimplemented
  Vanish:
    description: Vanish into the void!
    usage: /Vanish

  # Chat
  GlobalChat:
    description: Talk in global-chat
    usage: /g <message>
    aliases: g
  Message:
    description: Privately message a player
    usage: /msg <player> <message>
    aliases:
      - msg
      - m
      - whisper
      - w
  Reply:
    description: Reply to the last player that sent you a private message
    usage: /r <message>
    aliases: r
  TeamChat:
    description: Talk in team-chat
    usage: /t <message>
    aliases: t

  # Donator
  JoinMessage:
    description: Sets your custom join message
    usage: /joinmsg <set | reset> [message]
    aliases: joinmsg
    permission: castlesiege.esquire
    permission-message: Only donators are permitted to use this command!
  LeaveMessage:
    description: Sets your custom leave message
    usage: /leavemsg <set | reset> [message]
    aliases: leavemsg
    permission: castlesiege.esquire
    permission-message: Only donators are permitted to use this command!
  Firework:
    description: Shoots a firework with your teams colour into the sky!
    usage: /firework
    aliases: fw
    permission: castlesiege.esquire
    permission-message: Only donators are permitted to use this command!

  # Duels
  Duel:
    description: Challenge a specified player to a duel
    usage: /duel <player>
    aliases: duel
    permission: castlesiege.noble
    permission-message: Only donators, noble or above can use this command!
  DuelAccept:
    description: Accept a duel from someone
    usage: /duelaccept <player>
    aliases: acceptduel

  # Gameplay
  Switch:
    description: Switches teams.
    usage: /switch [team name]
    aliases: sw
  Suicide:
    description: commit die
    usage: /suicide
    aliases: sui
  Bounty:
    description: Add a bounty to a player
    usage: /bounty <player> [amount]
  Settings:
    description: Check or update your settings
    usage: /settings [setting] [value]
  Boosters:
    description: Check your boosters or use one
    usage: /booster [use] [id]
    aliases: booster
  VoteSkip:
    description: Vote to skip the current map
    usage: /voteskip [cancel]

  # Info
  CoinMultiplier:
    description: Shows the active coin multiplier
    usage: /coinmultiplier
  Coins:
    description: Shows the player's coins
    usage: /coins
  Discord:
    description: Gives the link to our discord
    usage: /discord
  Maps:
    description: Shows all maps in rotation
    usage: /maps
  MVP:
    description: Shows the current MVP(s)
    usage: /mvp(s)
    aliases: mvps
  MyStats:
    description: Opens a book that shows your stats
    usage: /mystats
  Ping:
    description: Shows your current ping
    usage: /ping
  Rules:
    description: Shows the rules
    usage: /rules
  Secrets:
    description: Shows the secrets
    usage: /secrets
  Teams:
    description: Shows the size and name of all teams on the current map
    usage: /teams
  Whois:
    description: Returns all previous names of a player!
    usage: /whois

  # Leaderboards
  Top:
    description: Shows the score leaderboard
    usage: /top [position]
    aliases:
      - toplist
      - topscore
      - leaderboard
  TopAssists:
    description: Shows the assists leaderboard
    usage: /topassists [position]
  TopCaptures:
    description: Shows the captures leaderboard
    usage: /topcaptures [position]
  TopDeaths:
    description: Shows the deaths leaderboard
    usage: /topdeaths [position]
  TopKDR:
    description: Shows the kdr leaderboard
    usage: /topkdr [position]
  TopKills:
    description: Shows the kills leaderboard
    usage: /topkills [position]
  TopSupports:
    description: Shows the supports leaderboard
    usage: /topsupports [position]
  TopHeals:
    description: Shows the heals leaderboard
    usage: /topheals [position]
  TopDonators:
    description: Shows the donator leaderboard
    usage: /topdonators [position]
  TopMatch:
    description: Shows the leaderboard for the current game
    usage: /topmatch [category] [position]
    aliases:
      - topgame
  TopTeam:
    description: Shows the leaderboard for your current team
    usage: /topteam [category] [position]
  Bounties:
    description: Shows the bounties leaderboard
    usage: /bounties [position]
    aliases:
      - topbounty

  # Staff - Currencies
  AddCoins:
    description: Add to a player's coins
    usage: /addcoins <player> <amount> [verbose]
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  SetCoins:
    description: Sets a player's coins
    usage: /setcoins <player> <amount> [verbose]
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  SetCoinMultiplier:
    description: Sets the active coin multiplier
    usage: /setcoinmultiplier <multiplier>
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  TakeCoins:
    description: Take from a player's coins
    usage: /takecoins <player> <amount> [verbose]
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  # Staff - Boosters
  GrantBooster:
    description: Grants a booster to a player
    usage: /grantbooster <player> <type> <duration> [other_args]
    permission: castlesiege.moderator
    permission-message: You are now permitted to use this command!
    aliases:
      - grantboost

  # Staff - Punishments
  Ban:
    description: Ban a player
    usage: /ban <player> <time> <reason>
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  Kick:
    description: Kick a player from the server
    usage: /kick <player> <reason>
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  KickAll:
    description: Kick all players from the server
    usage: /kickall <reason>
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  Mute:
    description: Mute a player
    usage: /mute <player> <time> <reason>
    permission: castlesiege.chatmod
    permission-message: You are not permitted to use this command!
  Unban:
    description: Unban a banned player
    usage: /unban <player>
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  Unmute:
    description: Unmute a muted player
    usage: /unmute <player>
    permission: castlesiege.chatmod
    permission-message: You are not permitted to use this command!
  Warn:
    description: Warn a player
    usage: /warn <player> <reason>
    permission: castlesiege.chatmod
    permission-message: You are not permitted to use this command!

  # Staff - ...
  Broadcast:
    description: Send a special message to everyone on the server
    usage: /broadcast <message>
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  CSReload:
    description: Reloads the Castle Siege Plugin
    usage: /csreload
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  Curse:
    description: Manages the active curses
    usage: /curse [curse]
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  Fly:
    description: Toggle flight
    usage: /fly
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  SetStaffRank:
    description: Set a staff rank for a player
    usage: /setstaffrank <player> <rank>
    permission: castlesiege.admin
    permission-message: You are not permitted to use this command!
  GiveVote:
    description: Give a player vote rewards
    usage: /givevote <player> <vote>
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  NextMap:
    description: Skips the current map and goes directly to the next one
    usage: /nextmap
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  RankPoints:
    description: Manages a player's rank points
    usage: /rankpoints <player> <set | add | remove> <amount>
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  SetKit:
    description: Sets the kit for a player
    usage: /setkit <player> [kit]
    permission: castlesiege.developer
    permission-message: You are not permitted to use this command!
  SetKitLimit:
    description: Sets the player limit per team for a kit
    usage: /setkitlimit <kit> <limit>
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  SetMap:
    description: Skips to the specified map in the rotation
    usage: /setmap <map name>
    permission: castlesiege.developer
    permission-message: You are not permitted to use this command!
  SetTimer:
    description: Sets the time left on the map to the specified time
    usage: /settimer <mins> [seconds]
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
  StaffChat:
    description: Talk in staff-chat
    usage: /s <message>
    aliases: s
    permission: castlesiege.chatmod
    permission-message: You are not permitted to use this command!
  ToggleRank:
    description: Switch between staff and donator rank
    usage: /togglerank
    permission: castlesiege.chatmod
    permission-message: You are not permitted to use this command!
  ToggleFree:
    description: Disables/Enables free kits
    usage: /togglefree [true/false]
    permission: castlesiege.moderator
    permission-message: You are not permitted to use this command!
    aliases:
    - togglenolimits
  Spectate:
    description: Makes you, or another player, a spectator.
    usage: /spectate [player]
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  ForceSwitch:
    description: Forefully switches a player to a different team
    usage: /forceswitch <player> [team name]
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  ToggleSwitching:
    description: Disables/Enables non-forceful switching
    usage: /toggleswitching [true/false]
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  Start:
    description: Ends the current timer phase
    usage: /start
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
  SetTag:
    description: Set a nametag prefix
    usage: /settag <tag>
    permission: castlesiege.developer
  ToggleForcedRandom:
    description: Disables/Enables forced randomDeath setting
    usage: /toggleforcedrandom [true/false]
    permission: castlesiege.chatmod+
    permission-message: You are not permitted to use this command!
    aliases:
      - togglerandom

  # Donations
  Unlockkit:
    description: Unlocks a kit for a player.
    usage: /unlockkit <Player Name> <add/remove> <Kit Name> <Time> <IsDonated:true/false>
    permission: castlesiege.developer
    permission-message: Try /buykit instead
  Webshop:
    description: Displays the link to support the server.
    usage: /Webshop
    aliases:
      - donate
      - kofi
      - ko-fi
      - support
      - shop
  Coinshop:
    description: Open the coinshop for the player.
    usage: /coinshop
  buykit:
    description: Buy a kit with coins
    usage: /buykit <kit> [player]

  # Kits
  Random:
    description: Selects a random kit from those you own
    usage: /random
  Kit:
    description: Open the GUI for selecting kits
    usage: /kit <category>
  Alchemist:
    description: Selects the alchemist kit
    usage: /alchemist
  Archer:
    description: Selects the archer kit
    usage: /archer
  Armorer:
    description: Selects the armorer kit
    usage: /armorer
  Berserker:
    description: Selects the berserker kit
    usage: /berserker
  BattleMedic:
    description: Selects the battle medic kit
    usage: /battlemedic
  Barbarian:
    description: Selects the barbarian kit
    usage: /barbarian
  Bannerman:
    description: Selects the bannerman kit
    usage: /bannerman
  Cavalry:
    description: Selects the cavalry kit
    usage: /cavalry
  Camelrider:
    description: Selects the camel rider kit
    usage: /camelrider
  Chef:
    description: Selects the chef kit
    usage: /chef
  Constructor:
    description: Selects the constructor kit
    usage: /constructor
  RoyalCryptsFallen:
    description: Selects the Fallen kit for Royal Crypts as Fallen
    usage: /royalcryptsfallen
  Crossbowman:
    description: Selects the crossbowman kit
    usage: /crossbowman
  ConwyLongbowman:
    description: Selects the Conwy longbowman kit for the Rebellion
    usage: /ConwyLongbowman
  ConwyRoyalKnight:
    description: Selects the Conwy royal knight kit for the English
    usage: /conwyroyalknight
  ConwyArbalester:
    description: Selects the Conwy arbalester kit for the English
    usage: /conwyarbalester
  Engineer:
    description: Selects the engineer kit
    usage: /engineer
  ThunderstoneElytrier:
    description: Selects the Elytrier kit for Thunderstone Guard
    usage: /thunderstoneelytrier
  Executioner:
    description: Selects the executioner kit
    usage: /executioner
  FireArcher:
    description: Selects the firearcher kit
    usage: /firearcher
  FirelandsAbyssal:
    description: Selects the Abyssal kit from firelands for the Burning Legion
    usage: /firelandsabyssal
  FirelandsHellsteed:
    description: Selects the Hellsteed kit from firelands for the Burning Legion
    usage: /firelandshellsteed
  Halberdier:
    description: Selects the halberdier kit
    usage: /halberdier
  Hypaspist:
    description: Selects the hypaspist kit
    usage: /hypaspist
  HelmsDeepUrukBerserker:
    description: Selects the Berserker kit on Helm's Deep
    usage: /helmsdeepberserker
  HelmsdeepLancer:
    description: Selects the Lancer kit on Helm's Deep
    usage: /helmsdeeplancer
  HommetLongbowman:
    description: Selects the Longbowman kit on Hommet
    usage: /HommetLongbowman
  HommetAxeman:
    description: Selects the Axeman kit on Hommet
    usage: /HommetAxeman
  HelmsdeepRangedCavalry:
    description: Selects the Ranged Cavalry kit on Helm's Deep
    usage: /helmsdeeprangedcavalry
  Ladderman:
    description: Selects the ladderman kit
    usage: /ladderman
  Maceman:
    description: Selects the maceman kit
    usage: /maceman
  Medic:
    description: Selects the medic kit
    usage: /medic
  Moriabonecrusher:
    description: Selects the Bonecrusher kit for Moria
    usage: /moriabonecrusher
  MoriaWindlancer:
    description: Selects the Windlancer kit for Moria
    usage: /moriawindlancer
  Moriaguardian:
    description: Selects the Guardian kit for Moria
    usage: /moriaguardian
  Moriacavetroll:
    description: Selects the Cave Troll kit for Moria
    usage: /moriacavetroll
  Moriaaxethrower:
    description: Selects the Axe Thrower kit for Moria
    usage: /moriaaxethrower
  Moriaorc:
    description: Selects the Moria Orc kit for Moria
    usage: /moriaorc
  Priest:
    description: Selects the Priest kit
    usage: /priest
  Paladin:
    description: Selects the Paladin kit
    usage: /paladin
  Ranger:
    description: Selects the ranger kit
    usage: /ranger
  Rogue:
    description: Selects the rogue kit
    usage: /rogue
  Scout:
    description: Selects the scout kit
    usage: /scout
  Shieldman:
    description: Selects the shieldman kit
    usage: /shieldman
  Skirmisher:
    description: Selects the skirmisher kit
    usage: /skirmisher
  Spearman:
    description: Selects the spearman kit
    usage: /spearman
  Spearknight:
    description: Selects the spearknight kit
    usage: /spearknight
  Swordsman:
    description: Selects the swordsman kit
    usage: /swordsman
  Sorcerer:
    description: Selects the sorcerer kit
    usage: /sorcerer
  Vanguard:
    description: Selects the vanguard kit
    usage: /vanguard
  Viking:
    description: Selects the viking kit
    usage: /viking
  Warbear:
    description: Selects the warbear kit
    usage: /warbear
  Warhound:
    description: Selects the warhound kit
    usage: /warhound
  Warlock:
    description: Selects the warlock kit
    usage: /warlock
