# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        overwrite-settings: false
        settings-path: $GITHUB_WORKSPACE/settings.xml # location for the settings.xml file

    - name: Create custom settings.xml
      uses: whelk-io/maven-settings-xml-action@v22
      with:
        output_file: $GITHUB_WORKSPACE/settings.xml
        repositories: >
          [
            {
              "id": "github-global",
              "url": "https://maven.pkg.github.com/AdminHuntifi/ConwyMC-global",
              "snapshots": {
                "enabled": "true"
              }
            }
          ]
        servers: >
          [
            {
              "id":"github-global",
              "username":"Greenfoot5",
              "password":"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"
            }
          ]

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
